### ISSUE TITLE
Failed when creating destination directory

### ISSUE THREAD

**Issue by Diamond427** [Diamond427/image-process-uuid#1]
```
Traceback (most recent call last):
  File "e:\Project\2024\drone.uuid-fname-change\main.py", line 4, in <module>
    convert_files(
  File "e:\Project\2024\drone.uuid-fname-change\convert.py", line 39, in convert_files
    Logger.info(f"Directory {dst_dir} created.")
TypeError: Logger.info() missing 1 required positional argument: 'str'
```

**Comment by Diamond427** [comment]
Error fixed
changed `Logger` to `logger` 😁
